import operator
import sqlite3
import os
import uuid
from typing import TypedDict, Any, List, Annotated, Literal
from dataclasses import dataclass

from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.store.memory import InMemoryStore
from langgraph.runtime import Runtime
from langgraph.types import Send, Command, interrupt

# --- 1. MEMORY SCHEMAS ---
@dataclass
class Context:
    user_id: str

class GraphState(TypedDict):
    event_data: dict
    plan: dict
    schedule: Any
    audit_log: Annotated[List[str], operator.add] 
    completed_work: Annotated[list[dict], operator.add] 
    agent_outputs: dict 
    user_feedback: str

# --- 2. THE UNIVERSAL ORCHESTRATOR-WORKER SUBGRAPH ---
class ExecutionState(TypedDict):
    event_data: dict
    schedule: list
    dynamic_tasks: list[dict] 
    completed_work: Annotated[list[dict], operator.add] 

class WorkerState(TypedDict):
    task: dict
    event_data: dict
    schedule: list

def build_execution_subgraph(marketing, email, budget_agent, volunteer_agent, sponsor_agent):
    sub_workflow = StateGraph(ExecutionState)

    async def master_orchestrator(state: ExecutionState):
        """Analyzes the event and dynamically creates a universal task list."""
        tasks_to_spawn = [
            {"domain": "marketing", "specifics": "Twitter Announcement Thread"},
            {"domain": "marketing", "specifics": "LinkedIn Professional Post"},
            {"domain": "email", "specifics": "Draft Initial Welcome Invite"},
            {"domain": "budget", "specifics": "Calculate Venue & Catering Estimates"},
            {"domain": "volunteer", "specifics": "Assign Registration Desk Shifts"},
            {"domain": "sponsor", "specifics": "Draft Tier 1 Tech Sponsors Pitch"}
        ]
        return {"dynamic_tasks": tasks_to_spawn}

    def assign_universal_workers(state: ExecutionState):
        """Spawns a unique worker for EVERY task generated by the orchestrator."""
        return [
            Send("domain_worker", {
                "task": task, 
                "event_data": state["event_data"], 
                "schedule": state.get("schedule", [])
            }) 
            for task in state["dynamic_tasks"]
        ]

    async def domain_worker(state: WorkerState):
        """The universal worker that routes the micro-task to the correct agent class."""
        task = state["task"]
        domain = task["domain"]
        specifics = task["specifics"]
        
        if domain == "marketing":
            result = await marketing.generate_campaign(state["event_data"], specifics)
        elif domain == "email":
            result = await email.draft_invites(state["event_data"], state["schedule"], specifics)
        elif domain == "budget":
            result = await budget_agent.calculate(state["event_data"],state["schedule"], specifics)
        elif domain == "volunteer":
            result = await volunteer_agent.assign_shifts(state["event_data"], state["schedule"], specifics)
        elif domain == "sponsor":
            result = await sponsor_agent.draft_sponsorships(state["event_data"], specifics)
        else:
            result = f"Completed unknown task: {specifics}"

        return {"completed_work": [{"domain": domain, "task": specifics, "output": result}]}

    # Map-Reduce flow
    sub_workflow.add_node("master_orchestrator", master_orchestrator)
    sub_workflow.add_node("domain_worker", domain_worker)
    sub_workflow.add_edge(START, "master_orchestrator")
    sub_workflow.add_conditional_edges("master_orchestrator", assign_universal_workers, ["domain_worker"])
    sub_workflow.add_edge("domain_worker", END)
    
    return sub_workflow.compile(checkpointer=False)


# --- 3. BUILD THE STREAMLINED MAIN GRAPH ---
# Note: Added 'updater_agent' to the dependencies
def build_graph(planner, scheduler, marketing, email, budget_agent, volunteer_agent, sponsor_agent, updater_agent):
    workflow = StateGraph(GraphState, context_schema=Context)

    async def run_planner(state: GraphState, runtime: Runtime[Context]) -> Command[Literal["scheduler"]]:
        event_data = state["event_data"]
        
        namespace = (runtime.context.user_id, "past_events")
        memories = await runtime.store.asearch(namespace, query=event_data.get('name', ''), limit=3)
        event_data["historical_context"] = "\n".join([m.value.get("event_summary", "") for m in memories]) if memories else ""
            
        plan_list = await planner.generate_multiple_plans(event_data, count=1)
        await runtime.store.aput(namespace, str(uuid.uuid4()), {"event_summary": f"Planned {event_data.get('name')}"})

        return Command(
            update={"plan": plan_list[0], "audit_log": ["Zero-shot plan generated."]},
            goto="scheduler"
        )

    async def run_scheduler(state: GraphState) -> Command[Literal["execution_phase"]]:
        schedule = await scheduler.create_schedule(state["plan"])
        
        # ROUTING: Instead of human review, immediately draft all assets!
        return Command(
            update={"schedule": schedule},
            goto="execution_phase"
        )

    async def finalize_results(state: GraphState) -> Command[Literal["human_review"]]:
        raw_work = state.get("completed_work", [])
        outputs = {
            "marketing": [w for w in raw_work if w["domain"] == "marketing"],
            "emails": [w for w in raw_work if w["domain"] == "email"],
            "operations": [w for w in raw_work if w["domain"] not in ["marketing", "email"]]
        }
        return Command(update={"agent_outputs": outputs}, goto="human_review")

    def human_review(state: GraphState) -> Command[Literal["__end__", "updater_node", "planner", "human_review"]]:
        """User Input Node: Pauses graph to review schedule AND drafted outputs."""
        
        # Pauses until UI posts a payload
        feedback = interrupt("Review everything. Edit directly, chat to modify, or approve.")
        
        action = feedback.get("action", "prompt")
        
        if action == "approve":
            # 🚀 Proceed to END (or you can route to a 'send_emails' node)
            return Command(update={"audit_log": ["Approved all assets."]}, goto=END)
        
        elif action == "direct_edit":
            # 🚀 User typed directly into the dashboard UI and hit save. Do NOT replan.
            return Command(
                update={
                    "schedule": feedback.get("schedule", state["schedule"]),
                    "agent_outputs": feedback.get("agent_outputs", state["agent_outputs"]),
                    "audit_log": ["Manual direct edits applied."]
                },
                goto="human_review" # Loop back to let them see it confirmed
            )
            
        elif action == "prompt":
            # 🚀 User typed "Delay by 2 hours" or "Change speaker". Route to targeted Updater!
            return Command(
                update={"user_feedback": feedback.get("message", "")},
                goto="updater_node"
            )
            
        else: # action == "replan_all"
            # 🚀 ONLY if user explicitly wants to tear it all down
            return Command(
                update={"event_data": {"user_constraints": feedback.get("message", "")}, "completed_work": []},
                goto="planner"
            )

    async def updater_node(state: GraphState) -> Command[Literal["human_review"]]:
        """LLM node that smartly mutates specific parts of state WITHOUT full replan."""
        feedback = state["user_feedback"]
        
        # Pseudo-code: updater_agent receives current state and instructions, applies delta
        new_schedule, new_outputs = await updater_agent.process_update(
            instructions=feedback, 
            schedule=state.get("schedule"), 
            outputs=state.get("agent_outputs")
        )
        
        return Command(
            update={"schedule": new_schedule, "agent_outputs": new_outputs, "audit_log": [f"Updater applied: {feedback}"]},
            goto="human_review"
        )

    # Register Nodes
    workflow.add_node("planner", run_planner)
    workflow.add_node("scheduler", run_scheduler)
    
    execution_subgraph = build_execution_subgraph(marketing, email, budget_agent, volunteer_agent, sponsor_agent)
    workflow.add_node("execution_phase", execution_subgraph)
    workflow.add_node("finalize", finalize_results)
    
    workflow.add_node("human_review", human_review)
    workflow.add_node("updater_node", updater_node)

    # Automatically start at planner, let Command routing handle the rest
    workflow.add_edge(START, "planner")

    # Persistence
    class AsyncSqliteSaverBridge(SqliteSaver):
        async def aget_tuple(self, config): return self.get_tuple(config)
        async def aput(self, config, checkpoint, metadata, new_versions): return self.put(config, checkpoint, metadata, new_versions)
        async def aput_writes(self, config, writes, task_id): return self.put_writes(config, writes, task_id)

    os.makedirs(os.path.join(os.getcwd(), "memory"), exist_ok=True)
    conn = sqlite3.connect(os.path.join(os.getcwd(), "memory", "swarm_threads.sqlite"), check_same_thread=False)
    
    return workflow.compile(
        checkpointer=AsyncSqliteSaverBridge(conn), 
        store=InMemoryStore()
    )